# Generated by Django 5.1.4 on 2024-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='award_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='award_description',
            field=models.TextField(blank=True, help_text="Describe the reward you're offering for finding your item", null=True),
        ),
    ]
